<div class="footer">
	<div class="wrap clear">
		<div class="works">
			<p class="bold">全国服务热线</p>
			<p class="bold">400-8084-3378</p>
			<p>上班时间 周一至周五</p>
			<p>早9:00－晚11:00</p>
			<p>紧急联系电话: 18757599327</p>
		</div>

		<ul class="ft-list">
			<li class="ftt">购物流程</li>
			<li><a href="#">出价竞拍</a></li>
			<li><a href="#">第一次付款</a></li>
			<li><a href="#">通知出货</a></li>
			<li><a href="#">第二次付款</a></li>
		</ul>
		<ul class="ft-list">
			<li class="ftt">支付／配送</li>
			<li><a href="#">充值说明</a></li>
			<li><a href="#">费用说明</a></li>
			<li><a href="#">日本输出</a></li>
			<li><a href="#">国际运输</a></li>
		</ul>
		<ul class="ft-list">
			<li class="ftt">售后问题</li>
			<li><a href="#">问题商品</a></li>
			<li><a href="#">弃标处理</a></li>
			<li><a href="#">海关关税</a></li>
			<li><a href="#">退款操作</a></li>
		</ul>
		<ul class="ft-list">
			<li class="ftt">关于我们</li>
			<li><a href="#">公司介绍</a></li>
			<li><a href="#">拍卖平台特色</a></li>
			<li><a href="#">会员约定条款</a></li>
			<li><a href="#">隐私权政策</a></li>
		</ul>
		<div class="ewm">
			<img src="../images/1514811694.png" alt="">
			<p>体验11区代拍乐趣</p>
		</div>
	</div>
</div>