<div class="site-nav site-nav-status-login">
	<div class="site-nav-bd clear">
		<!-- <div class="site-nav-bd-l">
			欢迎您，1041760346
			<a href="#" class="site-nav-bd-equit nav-link">[退出]</a>
			<a href="#" class="site-nav-bd-email nav-link">
				<img src="../images/sitetopemail.png" width="21"> 新邮件 0
			</a>
		</div> -->
		<div class="site-nav-bd-l">
			欢迎您来到11区
			<a href="#" class="nav-link">登陆</a>
			<a href="#" class="nav-link">免费注册</a>
			<a href="#" class="nav-link">微信登陆</a>
			<a href="#" class="nav-link">QQ登陆</a>
		</div>
		<div class="site-nav-bd-r">
			<div class="site-nav-bd-msg js-scorll-text">
				<ul>
					<li><a href="#">双11购物狂欢节1</a></li>
					<li><a href="#">双11购物狂欢节2</a></li>
					<li><a href="#">双11购物狂欢节3</a></li>
					<li><a href="#">双11购物狂欢节3</a></li>
					<li><a href="#">双11购物狂欢节6</a></li>
				</ul>
			</div>
			<div class="site-nav-bd-hl">
				今日汇率：1日元＝0.061RMB
			</div>
		</div>

	</div>
</div>
