<div class="top">
	<div class="top-wrap clear">
		<div class="yahoo-logo">
			<img src="../images/logo_h80.png" alt="logo" width="243" />
		</div>
		<div class="yahoo-search">
			<div class="search-wrap">
				<div class="search-bd clear">
					<div class="search-img-tag">
						<img src="../images/ssltbbq.png" />
					</div>
					<div class="search-panel">
						<form class="search-form clear" target="_top" id="J_YSearchForm" action="#">
							<div class="search-input">
								<input type="text" class="input" placeholder="请输入中文关键词或拍卖商品链接">
							</div>
							<select class="search-select" name="" id="">
								<option value="1" selected>日文</option>
								<option value="2" selected>中文</option>
							</select>
							<button class="search-button"><img src="../images/searc_icon.png" width="20" /></button>
						</form>
					</div>
				</div>
				<div class="search-ft">
					<a href="#">日本铁壶</a>
					<a href="#">二手尽头</a>
					<a href="#">古钱币</a>
					<a href="#">邮票</a>
					<a href="#">珠宝原石</a>
					<a href="#">二手名表</a>
					<a href="#">字画</a>
					<a href="#">古董瓷器</a>
				</div>
			</div>
		</div>
		<ul class="yahoo-fir-link clear">
			<li>
				<a href="#">
					<div class="yfl-iconbox"><i class="iconfont icon-qq"></i></div>
					<div class="yfl-text">联系客服</div>
				</a>
			</li>
			<li>
				<a href="#">
					<div class="yfl-iconbox"><i class="iconfont icon-shuqian"></i></div>
					<div class="yfl-text">帮助中心</div>
				</a>
			</li>
			<li>
				<a href="#">
					<div class="yfl-iconbox"><i class="iconfont icon-yonghuzhongxin"></i></div>
					<div class="yfl-text">会员中心</div>
				</a>
			</li>
		</ul>
		<div class="tel">全国服务热线：4008-0843-378</div>
	</div>
</div>